name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Test and Upload Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Test
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test_results
          path: |
            build/reports/tests/**
            */build/reports/tests/**
          retention-days: 10
      - name: Build
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew publishAllPublicationsToSonatypeRepository
