name: TestPullRequest

on:
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run Tests
        run: ./gradlew test
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: commitTestResults
          path: |
            build/reports/tests/**
            */build/reports/tests/**
          retention-days: 10